# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Weijie Yang
title: UC Berekely Data Science Master | JPMorgan Analyst
email: raphaelyang1998@berkeley.edu
website: https://raphaelyangwj.github.io/raphael-cv/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  RaphaelYangWJ
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Weijie Yang, a data science enthusiast with a Master’s in Information and Data Science from the University of California, 
  Berkeley. My academic path has been enriched by projects like using deep learning for global environmental challenges and 
  developing ecological models. I am passionate about exploring and working on challenging academic researches from the perspective 
  of data science and hope to contribute my effort to the technology and data improvement.

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Berkeley
        caption: 2022 Sep - Present (United States)
        sub_title: MSc Information and Data Science (STEM)
        description: | # this will include new lines to allow paragraphs
          - <strong>GPA</strong>: 3.9 / 4.0
          - <strong>Core Modules</strong>: 
              - Applied Machine Learning (A, 4.0)
              - Research Design & Applications for Data & Analysis (A, 4.0)
              - Fundamentals of Data Engineering (A, 4.0)
              - Statistics for Data Science (B+, 3.8)
              - Introduction to Data Science Programming (Waiver Exam Passed)
              - Computer Vision (In progress)


  - title: Academic Research - Global Wildfire Prediction using Convolutional DNN
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lawrence Berkeley National Laboratory
        sub_title: Machine Learning Researcher
        link: https://github.com/RaphaelYangWJ/wildfire-prediction/tree/main
        description: | # this will include new lines to allow paragraphs
          - <strong>Wildfire Image Processing:</strong> Transformed climate data (NC4 format) by Numpy to three-dimensional matrices including temporal and geospatial information. Performed matrix transformations to map the data into RGB 3-channel image arrays, enhancing the differentiation of burnt regions through intensified RGB color values to bolster the neural network's image recognition capabilities.
          - <strong>Feature Extraction and Image Convolution:</strong> Extracted 13 key features including precipitation, burnt area, tree coverage, population density, and lightning frequency. Employed convolution and average pooling techniques to capture neighboring pixel feature information to enrich feature representation. Implemented data imputation, normalization, dimensionality reduction, and tensor transformation to optimize model input.
          - <strong>Neural Networks Modeling:</strong> Constructed DNN and CNN using PyTorch, with the Tanh activation function and MSE loss function. Integrated Dropout layers to avoid overfitting. Achieved 75% accuracy on the validation set with the Convolutional DNN model, marking a 5% improvement over normal neural networks. Plans are underway to explore the use of Transformer and RNN architectures to further enhance model performance.
          - <strong>Model Interpretability and Attribution:</strong> Analyzed attributions on the input features of the established neural network models, assessing the contribution of factors such as temperature, wind speed, and geographic location to wildfire predictions. Identified that wind force, fuel load, and the previous year's burnt area (seasonality factor) have significant contributions to wildfire forecasting.
        title: Lawrence Berkeley National Laboratoryfdfd
        sub_title: Machine Learning Researcherdfd
        link: https://github.com/RaphaelYangWJ/wildfire-prediction/tree/maindf
        description: | # this will include new lines to allow paragraphs
         21321321




  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.





# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
