# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Weijie Yang
title: UC Berekely Data Science Master | JPMorgan Analyst
email: raphaelyang1998@berkeley.edu
website: https://raphaelyangwj.github.io/raphael-cv/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  RaphaelYangWJ
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm Weijie Yang, a data science enthusiast with a Master’s in Information and Data Science from the University of California, 
  Berkeley. My academic path has been enriched by projects like using deep learning for global environmental challenges and 
  developing ecological models. I am passionate about exploring and working on challenging academic researches from the perspective 
  of data science and hope to contribute my effort to the technology and data improvement.

content:

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Berkeley
        caption: Sep. 2022 - Present (United States)
        sub_title: MSc Information and Data Science (STEM)
        description: | # this will include new lines to allow paragraphs
          - <strong>GPA</strong>: 3.9 / 4.0
          - <strong>Core Modules</strong>: 
              - Applied Machine Learning (A, 4.0)
              - Research Design & Applications for Data & Analysis (A, 4.0)
              - Fundamentals of Data Engineering (A, 4.0)
              - Statistics for Data Science (B+, 3.8)
              - Introduction to Data Science Programming (Waiver Exam Passed)
              - Computer Vision (In progress)
          </br>
          - <strong>Imperial College London</strong>: Master of Science in Economics and Strategy for Business (GPA: 3.72/4.0) | Sep. 2020 – Nov. 2021
          - <strong>Shanghai University</strong>: Bachelor of Science in International Economics and Trade (GPA: 3.51/4.0) | Sep. 2016 – Jul. 2020



  - title: Academic Research - Global Wildfire Prediction using Convolutional DNN
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lawrence Berkeley National Laboratory
        caption: Aug. 2023 – Present
        sub_title: Machine Learning Researcher
        link: https://github.com/RaphaelYangWJ/wildfire-prediction/tree/main
        description: | # this will include new lines to allow paragraphs
          - <strong>Wildfire Image Processing:</strong> Transformed climate data (NC4 format) by Numpy to three-dimensional matrices including temporal and geospatial information. Performed matrix transformations to map the data into RGB 3-channel image arrays, enhancing the differentiation of burnt regions through intensified RGB color values to bolster the neural network's image recognition capabilities.
          - <strong>Feature Extraction and Image Convolution:</strong> Extracted 13 key features including precipitation, burnt area, tree coverage, population density, and lightning frequency. Employed convolution and average pooling techniques to capture neighboring pixel feature information to enrich feature representation. Implemented data imputation, normalization, dimensionality reduction, and tensor transformation to optimize model input.
          - <strong>Neural Networks Modeling:</strong> Constructed DNN and CNN using PyTorch, with the Tanh activation function and MSE loss function. Integrated Dropout layers to avoid overfitting. Achieved 75% accuracy on the validation set with the Convolutional DNN model, marking a 5% improvement over normal neural networks. Plans are underway to explore the use of Transformer and RNN architectures to further enhance model performance.
          - <strong>Model Interpretability and Attribution:</strong> Analyzed attributions on the input features of the established neural network models, assessing the contribution of factors such as temperature, wind speed, and geographic location to wildfire predictions. Identified that wind force, fuel load, and the previous year's burnt area (seasonality factor) have significant contributions to wildfire forecasting.
        
  - title: Academic Research - DNN and Visualization for Multi-Agency Rocky Intertidal Networks
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of California, Santa Cruz
        caption: Aug. 2023 – Nov. 2023
        sub_title: Machine Learning Researcher
        link: https://raphaelyangwj.github.io/UCSC-MARINe-DS-Project/Websites/Navigation_page.html
        description: | # this will include new lines to allow paragraphs
          - <strong>Geospatial Coordinates Computation:</strong> Constructed a 3-dimensional matrix based on UAV-collected topographic data of intertidal sites, including latitude, longitude, and angles. Applied the Haversine Formula to precisely calculate the geospatial coordinates of each biological distribution point within the coordinate system, significantly enhancing data accuracy. Additionally, crafted a user interface using Tkinter and encapsulated the comprehensive program into a software application, successfully applied to data processing of over 8 intertidal sites.
          - <strong>Multi-classification Neural Networks Construction:</strong> Created a five-class deep neural network model to predict the probability of creature distribution at each coordinate point in the intertidal site, using relative sea-level height as the input feature. Implemented resampling techniques to ensure the balance of the dataset. The final model achieved a classification accuracy of 42.75%, substantially surpassing the baseline accuracy of 20%.
          - <strong>Interactive Visualization Website Development:</strong> Utilized Apache Echarts as graphing techniques to develop an interactive visualization website. The website displays the distribution of over 16 species across eight intertidal sites, including 3-dimensional topographic heatmaps, biological distribution change river maps, pie charts, and histograms. Constructed an interactive global map using GeoPandas. All research outcomes have been consolidated into the website, currently serving the university’s research staff and students, with plans for future integration into the official university website.



        
  - title: Course Research - Multi-modal Emotion Detection and Classification using Audio-Visual Data
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        link: https://github.com/RaphaelYangWJ/applied-learning
        description: | # this will include new lines to allow paragraphs
          - <strong>Visual Data Processing:</strong> Conducted temporal average frame rate sampling on all emotional videos, transforming each video into 6 images. Utilized OpenCV DNN ResNet for facial recognition and centered cropping of images, significantly enhancing feature quality.
          - <strong>Audio Data Processing:</strong> Transformed audio data into spectrograms and computed over 40 audio features including Mel-Frequency Cepstral Coefficients (MFCC), which served as input data for subsequent convolutional neural networks.
          - <strong>Multimodal Model Construction:</strong> Developed a multimodal model that simultaneously processes audio and visual inputs. Employed ConvLSTM2D to extract features from video data and Conv2D for feature extraction from audio spectrograms, integrating these features through fully connected layers. Additionally, experimented with transfer learning using VGG19 and YAMNet for audio imagery. The model achieved an accuracy of 52% on the validation set.



  - title: Course Research - US Flight Delays Prediction by Spark Machine Learning
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        link: https://github.com/RaphaelYangWJ/flight-delays
        description: | # this will include new lines to allow paragraphs
          - <strong>Big Data Cleaning and Processing:</strong> Utilized PySpark to merge datasets including all US flight information from 2015-2018, nationwide weather databases, annual holiday information, and natural disaster data. Performed data concatenation, deduplication, missing value removal, and outlier exclusion. Selected 19 effective features from a pool of 200 for subsequent modeling.
          - <strong>Machine Learning Modeling:</strong> Performed distributed data processing on the Azure platform. Experimented logistic regression, perceptron, and neural network models based on Spark, using input features such as departure and arrival airports, taxi-out time, aircraft carriers, and weather conditions to predict the probability of flight delays. Achieved an accuracy of 83.9% on the model's validation set.


  - title: Working Expeirence # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: J.P. Morgan
        caption: Mar. 2022 - Present
        sub_title: Rotation Analyst at Payments Dept. (Data Science Track)
        description: | # this will include new lines to allow paragraphs
          - <strong>China Advance FX Purchase Transformer Auto Monitoring Model (Modeling Developer)</strong>:
            - <strong>Awards:</strong> Champion of JPM Digital & Platform Services Excellence Awards & Champion of JPM APAC Payments Awards
            - <strong>Monitoring Model Development:</strong> Utilized Python as the programming language and SQL Server as the database to develop a monitoring model. This model processes daily client transaction data and payment instructions from the operations department, deducting foreign exchange quotas for various currencies from the database. Moreover, it automatically generates latest transaction quota reports each morning before trading begins and dispatches them to the operations, product, and sales teams.
            - <strong>Transformer-Based Trading Prediction Model Construction:</strong> Built a predictive model using client historical transaction data, including time, frequency, amount, currency as inputs. This Transformer-based model forecasts customer transaction volumes and quota consumption, providing predictive results to the sales and product teams for decision-making support regarding client quota setup. The model achieved a prediction accuracy of 67.3% for T+5 trading days.

          - <strong>Payments Whitelist Metrics Software –K-Means Machine Learning Techniques (Modeling Developer)</strong>:
            - <strong>Client Metrics Monitoring:</strong> Conducted client transaction metrics monitoring based on the past 2 years of payment transaction data from balance of payments statements. Calculated 36 metrics including transaction volume, ratio of income to payments, and concentration of transactions, and monitored these indicators. Historical data distributions were used to establish safe and risky thresholds. Detailed checks were performed on customers whose indexes exceeded safe monitoring ranges to ensure transaction security and compliance.
            - <strong>K-means Clustering Metrics Setup Model Construction:</strong> Plotted scatter graphs for all metrics and applied the K-means clustering algorithm to segment metrics into 3 groups. The 75th percentile of the group with the largest centroid and the group with the smallest centroid were designated as the upper and lower limits of the safe zone, respectively, while the 90th percentile was used to define the bounds of the risky zone. This methodology allowed the machine learning model to automatically determine zones for the 36 metrics, significantly reduce manual effort and time required for metrics setup. This functionality has been packaged into software for convenient use by sales and product departments.
            - <strong>Project Link:</strong> https://github.com/RaphaelYangWJ/whitelist-product


  - title: Skillsets # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        description: | # this will include new lines to allow paragraphs
          - <strong>Programming Language:</strong> Python (proficient in Numpy, Pandas, PyTorch, TensorFlow, Sklearn, Matplotlib), SQL, R
          - <strong>Deep Learning Models:</strong> Neural Networks, CNN, DNN, RNN, LSTM, Transformers
          - <strong>Machine Learning Models:</strong> Regression, Logistic Regression, Decision Trees, Support Vector Machines (SVM), and Multilayer Perceptron (MLP)
          - <strong>Big Data Framework:</strong> Spark (including PySpark), MapReduce, Hadoop
          - <strong>Platform:</strong> Amazon AWS, Google Dataproc, Microsoft Azure Databricks, GitHub


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
